version: "3"

services:
  radio:
    container_name: radio_api
    image: stdevel/radio_api:latest
    ports:
      - "5000:5000"
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - data:/opt/radio_api/instance
    restart: unless-stopped

volumes:
  data:
